defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            do_sitemap: true
            excerpt_seperator: <!--more-->
            category: general
            thumb: "https://ep8script.com/assets/img/ep8.png"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
        values:
            author_card: "https://ep8script.com/aboutme/"
            author: "Ep8Script"
            author_legal: "Jessica"

permalink: pretty
title: "Ep8Script's Blog"
paginate: 5
plugins: [jekyll-paginate]
url: "https://ep8script.com"
canon-url: "https://ep8script.com"
encoding: utf-8
